spring.application.name=sda-gateway
server.port=8007

logging.level.org.springframework.cloud.gateway=DEBUG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.httpclient.wiretap=true
spring.cloud.gateway.server.webflux.httpserver.wiretap=true

cloud.gateway.routes[0].id=sda-git
cloud.gateway.routes[0].uri=lb://sda-git
cloud.gateway.routes[0].predicates[0]=Path=/git/**
cloud.gateway.routes[0].filters[0]=RewritePath=/git/(?<segment>.*), /git/${\segment}

cloud.gateway.routes[1].id=sda-git-webhook
cloud.gateway.routes[1].uri=http://localhost:8008
cloud.gateway.routes[1].predicates[0]=Path=/webhook/**
cloud.gateway.routes[1].filters[0]=StripPrefix=0
#cloud.gateway.routes[1].filters[0]=RewritePath=/webhook/(?<segment>.*), /webhook/${\segment}

cloud.gateway.routes[2].id=sda-ai
cloud.gateway.routes[2].uri=http://localhost:8009
cloud.gateway.routes[2].predicates[0]=Path=/ai/**
cloud.gateway.routes[2].filters[0]=RewritePath=/ai/(?<segment>.*), /ai/${\segment}

cloud.gateway.routes[3].id=sda-ai-multiagent
cloud.gateway.routes[3].uri=http://localhost:8009
cloud.gateway.routes[3].predicates[0]=Path=/multiagent/**
cloud.gateway.routes[3].filters[0]=RewritePath=/multiagent/(?<segment>.*), /multiagent/${\segment}
