spring.application.name=sda-git
server.port=8008

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

git.owner=ankitagrahari
git.repo.name=smart-devops-assistant
git.api.url=https://api.github.com/
git.branch.name=master

# H2 Database
spring.datasource.url=jdbc:h2:mem:sda_db
# ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate (if using Spring Data JPA)
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=info
logging.level.org.apache.hc.client5.http=error
logging.level.jdk.event.security=error
logging.level.org.springframework=error